### PR TITLE
chore(ci): Consolidate workflow into just commands

### PR DESCRIPTION
**Pull request by m2Giles**

### CODE REVIEW

**Comment by m2Giles** [comment]
Need to add the just install action.

**Comment by m2Giles** [comment]
Building the image looks good now.

Need to test build-iso action.

**Comment by m2Giles** [comment]
This is now ready for review

**Comment by m2Giles** [comment]
Reran checks. Found one more scheduled instead of schedule.

Made sure it runs locally again.

**Review by bsherman — APPROVED** [review]
we won't know for sure if its perfect until we merge due to some last stage only on non-PR steps, but we have caught a few and in general this is looking great!

**Pull request merged**
