### PR TITLE
feat: ollama ujust script, some additions for removal verbs for the ollama and open-webui containers.

### PR DESCRIPTION
**Pull request by muddyfeather**
this is a first step on adding some actions to the ujust for ollama before potentially standardising this in bazzite too with another PR to bring "bazzite-tools.just" over. I've been using this, but i've seen others with the same opinion as me that i'd like to be able to mostly atomically clean up after it, as bazzite machines are often everything devices (so people are picky about things using their resources) I also can imagine a situation where in bazzite, people will want to tinker with this, but then remove and clear up afterwards because of the nature of the machine, and the users themselves are likely not as tech savvy as say aurora or bluefin people.
The script is a frankenstein now, but works in my test environment, backwards and forwards as necessary. I'm not sure what the established design conventions are for remove- verbs and how people expect it to work, but it's got an included "ollama help" to move things along. 

I'm sure this will help dozens of people ;)

### CODE REVIEW

**Comment by muddyfeather** [comment]
FYI, happy to redo, if we prefer install-ollama, install-open-webui, remove-ollama recipes as a convention!

**Comment by castrojo** [comment]
I'm hoping we can get some testing on this, I'm short on time lately. :(

**Comment by castrojo** [comment]
The weekly builds just passed so let's just get this into latest. Thanks for helping with this!

**Comment by muddyfeather** [comment]
No problems!

**Pull request merged**
