### PR TITLE
feat: Add Fedora 40 builds to Bluefin

### PR DESCRIPTION
**Pull request by dylanmtaylor**

### CODE REVIEW

**Comment by castrojo** [comment]
If you can do a quick update we should be good to go now!

**Comment by dylanmtaylor** [comment]
> If you can do a quick update we should be good to go now!

Awesome. What needs changed for it to pass?

**Comment by dylanmtaylor** [comment]
> If you can do a quick update we should be good to go now!
Can you retrigger the failed builds? I don't think this PR needs modified.

**Comment by noelmiller** [comment]
> > If you can do a quick update we should be good to go now!
> Can you retrigger the failed builds? I don't think this PR needs modified.

You need to resolve merge conflicts.

**Comment by dylanmtaylor** [comment]
Updated.

**Review by castrojo — APPROVED** [review]
Thanks, we're good to go!

**Comment by noelmiller** [comment]
> Thanks, we're good to go!

Uh, merge queue will catch the conflict right?

**Pull request merged**
