### PR TITLE
feat: seasonal variation in sunrise/sunset times for seasonal Bluefin backgrounds

### PR DESCRIPTION
**Pull request by Raindrac**
This PR changes the time at which the sun rises and sets in the seasonal Bluefin backgrounds to more closely match the variation in sunrise/sunset timing seen in real life. Daytime has a longer duration during summer and a shorter duration during winter.

Because the timing of sunsets and sunrises is dependent upon various factors, such as latitude and the specific date, choosing the exact time for the sunset and sunrise to begin for each background required some consideration.

Bluefin's seasonal backgrounds are inspired by the appearance of seasons in temperate, mid-latitude regions; for that reason, I chose to use the timings commonly experienced in mid-latitudes of around 40 - 45°. I averaged out the sunrise/sunset timing for each season to work around the variation within seasons. And to accommodate for how some mid-latitude regions implement daylight savings time, I chose a compromise for spring and summer that should feel close enough regardless of whether a specific location uses DST.

Overall, the timing of sunrises and sunsets in the seasonal Bluefin backgrounds should be much closer to the real-life timing for all regions which experience temperate seasons.

### CODE REVIEW

**Comment by Raindrac** [comment]
### Spring
12.5 hours of daylight, sunrise and sunset length of 2 hours
**Sunrise:** 6:00am (Fade begins at 5:00am, ends at 7:00am)
**Sunset:** 6:30pm (Fade begins at 5:30pm, ends at 7:30pm)

### Summer
13.5 hours of daylight, sunrise and sunset length of 2 hours
**Sunrise:** 5:45am (Fade begins at 4:45am, ends at 6:45am)
**Sunset:** 7:15pm (Fade begins at 6:15pm, ends at 8:15pm)

### Autumn
11.5 hours of daylight, sunrise and sunset length of 2 hours
**Sunrise:** 6:30am (Fade begins at 5:30am, ends at 7:30am)
**Sunset:** 6:00pm (Fade begins at 5:00pm, ends at 7:00pm)

### Winter
10.5 hours of daylight, sunrise and sunset length of 30 minutes
**Sunrise:** 7:00am (Fade begins at 6:45am, ends at 7:15am)
**Sunset:** 5:30pm (Fade begins at 5:15pm, ends at 5:45pm)
Note: Sunrise and sunset durations are shortened for winter to reduce the duration of the ghost dino effect. It has a little charm though, so I kept the duration to 30 minutes rather than making the transition between night and day only a couple seconds long.

**Comment by castrojo** [comment]
Thanks for this! Yeah the fading dino is one of those "you're in a snowstorm, did you see a Therizinosaur or is your mind playing tricks on you? Could have sworn I saw a Nanuqsaurus earlier too. I'm cold." 

I'd like to get this in for 3.0, did you do local testing? This wallpaper xml always scares me.

**Comment by Raindrac** [comment]
Yep, I performed local testing! Proud to have figured out how to build my own image and test it in a VM; last time I modified the summer background, I just tested by copying the backgrounds over to ~/.local/share. I tested the sunrise and sunset for each background, along with all 24 hours of the day.

**Review by castrojo — APPROVED** [review]
Thanks! LET'S GO.

**Pull request merged**
