### PR TITLE
fix: remove switch-input-source keybinding

### PR DESCRIPTION
**Pull request by p5**
This keybinding should be reserved for Search Light, so we need to unset the existing default usage of the keybind.

This is the second attempt at this, since the first attempt broke all dconf settings - restoring the system to a near stock GNOME shell.

### CODE REVIEW

**Review by m2Giles — COMMENTED** [review]
Empty string is disabled?

**Review by lauretano — CHANGES_REQUESTED** [review]
my error on the earlier pull request, the key name is switch-input-source-backward not backwards

**Comment by castrojo** [comment]
This ready for review?

**Comment by p5** [comment]
> This ready for review?

Give me 5 minutes to try to answer @m2Giles 's question, then will make it ready.  `dconf watch` isn't too helpful here, as it says it's just `[]`

**Comment by p5** [comment]
Applied these dconf settings on a clean install of Bluefin, and this is the end result, which is expected.

image


Unfortunately Search Light is not working right now, but maybe a reboot will re-apply the shortcuts?

**Review by m2Giles — APPROVED** [review]

**Pull request merged**
