### PR TITLE
feat: automatically use bootc to update system if locklayering is being used

### PR DESCRIPTION
**Pull request by tulilirockz**
This is supposed to be a small step to getting people using bootc more - This PR just implements a partial version of https://github.com/ublue-os/config/issues/279 on Bluefin

### CODE REVIEW

**Comment by karman011** [comment]
I think it would be better if you make it a custom command and disable rpm-ostree upgrade in topgrade.toml.

**Comment by castrojo** [comment]
Here's our topgrade config for reference: https://github.com/ublue-os/bluefin/blob/main/system_files/shared/usr/share/ublue-os/topgrade.toml

I know @bsherman has opinions on streamlining our usage of topgrade better so cc'ing him in.

**Comment by tulilirockz** [comment]
> I think it would be better if you make it a custom command and disable rpm-ostree upgrade in topgrade.toml.

Good idea! Ill just copy the topgrade config and remove the rpm_ostree module :p

**Comment by tulilirockz** [comment]
image
Using the approach you suggested seems to be working fine on my system! Very nice! @befanyt

**Comment by castrojo** [comment]
Don't merge until these land:

https://bodhi.fedoraproject.org/updates/FEDORA-2024-88b4110a60
https://bodhi.fedoraproject.org/updates/FEDORA-2024-246828877f

**Review by Malix-Labs — APPROVED** [review]

**Comment by castrojo** [comment]
Ok everything is in Fedora, last call!

**Review by Malix-Labs — APPROVED** [review]

**Review by Malix-Labs — APPROVED** [review]

**Review by castrojo — APPROVED** [review]

**Comment by Malix-Labs** [comment]
_sorry about the triple review, for some reason GitHub allows multiple review even if the code hasn't changed and I have a so poor bandwidth that clicking multiple time on the button just instantly `POST` multiple reviews_

**Comment by tulilirockz** [comment]
PR'd support for this [upstream](https://github.com/topgrade-rs/topgrade/pull/986) so that we don't need to use this workaround

**Pull request merged**
