### PR TITLE
feat: ublue-rollback-helper - add stable-daily to targets

### PR DESCRIPTION
**Pull request by dajmeister**
Adding stable-daily to the rebase helper options for https://github.com/ublue-os/bluefin/issues/1782

Possibly should update the message as well. Open to suggestions here. Below is one option although seems a little verbose.

`The default selection is gts, stable (weekly builds) and stable-daily (daily builds) are for enthusiasts, and latest is for testers`

Example from running it locally (rebasing from stable -> stable-daily)
```
./ublue-rollback-helper 
Choose your action.
Which Tag would you like to rebase to?
The default selection is gts, stable is for enthusiasts, and latest is for testers
Rebase Target is ghcr.io/ublue-os/bluefin-dx:stable-daily
Confirm Rebase
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:stable-daily
Importing: ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:stable-daily (digest: sha256:0d10f41a01a735797519b1c1fbe0b8a0fdfb6a3a7c11484b430e02b4bd114616)
ostree chunk layers already present: 61
ostree chunk layers needed: 11 (1.1 GB)
Fetching ostree chunk sha256:4439bd3dede3 (112.1 MB)... done
Fetching ostree chunk sha256:446cf5d07acb (144.9 MB)... done
Fetching ostree chunk sha256:966fe64c459e (150.7 MB)... done
Fetching ostree chunk sha256:e6f475c8082a (86.8 MB)... done
Fetching ostree chunk sha256:ac6738ab5132 (85.9 MB)... done
Fetching ostree chunk sha256:54a3cfab19f3 (39.4 MB)... done
Fetching ostree chunk sha256:62d6370aaaf7 (71.3 MB)... done
Fetching ostree chunk sha256:32518619f02c (63.1 MB)... done
Fetching ostree chunk sha256:d4f607332a2c (35.6 MB)... done
Fetching ostree chunk sha256:373785233ae9 (339.8 MB)... done
Fetching ostree chunk sha256:131e2a709fa6 (9.6 MB)... done
Staging deployment... done
Freed: 937.3 MB (pkgcache branches: 0)
Upgraded:
  devpod v0.5.20-1.fc40 -> v0.5.21-1.fc40
  kcli 99.0.0.git.202410142227.e28a501-0.fc40 -> 99.0.0.git.202410161200.72a798d-0.fc40
  kernel-tools 6.10.12-200.fc40 -> 6.11.3-200.fc40
  kernel-tools-libs 6.10.12-200.fc40 -> 6.11.3-200.fc40
  libgsf 1.14.51-4.fc40 -> 1.14.53-1.fc40
  libopenmpt 0.7.8-1.fc40 -> 0.7.10-1.fc40
  tailscale 1.76.0-1 -> 1.76.1-1
Changes queued for next boot. Run "systemctl reboot" to start a reboot
```

### CODE REVIEW

**Comment by castrojo** [comment]
Ooh! thanks for working on this:

> The default selection is gts, stable (weekly builds) and stable-daily (daily builds) are for enthusiasts, and latest is for testers

This seems fine, we may also want to spit out the docs url like we do in the motd: https://docs.projectbluefin.io/administration#upgrades-and-throttle-settings since that will always be up to date and gets improved over time.

**Comment by castrojo** [comment]
The table from the docs renders really nice with glow, maybe we should just inline it? Two birds with one stone? (Though let's get this in first and then we can fine tune it. 

image

**Comment by m2Giles** [comment]
Would be nice to programmatically get the Fedora and gnome versions

**Review by castrojo — APPROVED** [review]
Thanks!

**Pull request merged**
