### PR TITLE
chore(flatpaks): move to unified folder

### PR DESCRIPTION
**Pull request by tulilirockz**
This is kind of a nitpick but there is no techinical reason to have that anymore after the justfile rework by m2. This just looks a bit cleaner!

### CODE REVIEW

**Comment by tulilirockz** [comment]
Doesn't have any functional changes when building the ISOs and the ujust recipe should work fine also
image

**Comment by tulilirockz** [comment]
Thinking about it - This makes the old images not be able to do `ujust install-system-flatpaks`...

**Comment by tulilirockz** [comment]
If it would be better, I can make it so the `aurora_flatpaks`/`bluefin_flatpaks` folders are still gonna be there until the next GTS build or something

**Comment by castrojo** [comment]
Why are we making this change? Do we really need to change this?

**Comment by tulilirockz** [comment]
Should've proposed this before making the PR LOL - But no, this is most likely not necessary. Should I just close it?

**Comment by castrojo** [comment]
Yeah let's just focus on fixing bugs and clean up, we don't need to rearrange the furniture unless we have to. Thanks!

**Pull request closed without merging**
