### PR TITLE
chore(ci): Update to latest version of Build-Container-Installer and include building Aurora ISOs

### PR DESCRIPTION
**Pull request by noelmiller**
# Summary

This PR includes a number of things in it. 
1. Using the latest pinned version of Build Container Installer
2. Using a folder upload rather than individual file uploads
3. Creates split workflows to build ISOs

# Blockers

- [x] Secrets needed for Aurora Buckets
- [x] Test ISOs that are being built with main
- [x] Pinned version of Build-Container Installer needs to be released
- [x] Pin to versioned release
- [x] Test ISOs built with pinned release version

### CODE REVIEW

**Comment by m2Giles** [comment]
We have our flatpak lists duplicated

**Comment by castrojo** [comment]
Yeah and shouldn't we use the `silverblue` and `kinoite` instead of kde_flatpaks, gnome_flatpaks, and aurora_flatpaks so we match how we organize the rest of the repo?

**Comment by noelmiller** [comment]
> We have our flatpak lists duplicated

I think those got reintroduced on a merge from my branch. Removed them.

**Comment by noelmiller** [comment]
> Yeah and shouldn't we use the `silverblue` and `kinoite` instead of kde_flatpaks, gnome_flatpaks, and aurora_flatpaks so we match how we organize the rest of the repo?

I guess I would want a second opinion on this @m2Giles. I personally think it's clearer to have them delineated between as bluefin_flatpaks and aurora_flatpaks personally.

**Comment by noelmiller** [comment]
I'm going to say this is ready for review. The main blocker for building aurora ISOs shouldn't affect this going in. We can always fix it if the bucket name for aurora needs to be adjusted.

**Comment by m2Giles** [comment]
I'm impartial to the names for the flatpak dirs.

One reason to stay with the brand names is that we invoke the workflow with this names. But we already use the kinoite/silverblue names inside as variables.

**Review by NiHaiden — COMMENTED** [review]
Looks great to me, thanks Noel!

**Review by m2Giles — APPROVED** [review]
Let's get Aurora Shipping!

**Pull request merged**
