### PR TITLE
feat: add Samsung ULD drivers from Negativo

### LINKED ISSUE #1550: Add Samsung Unified Linux Driver .rpm driver pack from negativo17 repository
### Describe the package

Is it possible to add drivers for some Samsung printers, from my knowledge most if not all Samsung printers need **uld** - **Samsung Unified Linux Driver** - https://ftp.hp.com/pub/softlib/software13/printers/SS/SL-C4010ND/uld_V1.00.39_01.17.tar.gz

I know that ublue team use some of the stuff that negativo17 host and he also host a .rpm packaged for that driver pack - https://negativo17.org/samsung-unified-linux-driver-printers-scanners/

Repository link - https://negativo17.org/repos/uld/fedora-40/x86_64/

I personally tested them multiple times, and they do work.

### Image

Bluefin, Aurora and Bazzite(If Bazzite maintainers want it!)

### PR DESCRIPTION
**Pull request by tulilirockz**
Should fix #1550 and #1604 - Although this seems like it should be added upstream-er, like on ublue-os/main or something.

### CODE REVIEW

**Comment by fiftydinar** [comment]
Negativo uld repo is not needed, because negativo multimedia already covers it, as everything else from Negativo (multimedia is an all-in-on repo)

**Review by fiftydinar — APPROVED** [review]

**Review by bsherman — COMMENTED** [review]
Seems a reasonable add for Bluefin given other printer specific drivers are already included.

@castrojo ?

I don't think this should be in main, but bluefin works.

**Comment by castrojo** [comment]
+1 on this, a few users have asked for these.

**Comment by NiHaiden** [comment]
Let's ship this.

**Comment by bsherman** [comment]
I tested a local build where instead of keeping this in the `packages.json` I later installed it standalone to see if there was some error i was missing in the wall of text:

```
+ rpm-ostree install uld
Enabled rpm-md repositories: charm tailscale-stable copr:copr.fedorainfracloud.org:ublue-os:staging copr:copr.fedorainfracloud.org:sentry:switcheroo-control_discrete copr:copr.fedorainfracloud.org:che:nerd-fonts copr:copr.fedorainfracloud.org:ublue-os:akmods fedora-multimedia fedora-cisco-openh264 fedora updates updates-archive
Importing rpm-md...done
rpm-md repo 'charm' (cached); generated: 2024-09-12T18:37:10Z solvables: 456
rpm-md repo 'tailscale-stable' (cached); generated: 2024-11-04T22:43:21Z solvables: 112
rpm-md repo 'copr:copr.fedorainfracloud.org:ublue-os:staging' (cached); generated: 2024-11-04T04:02:06Z solvables: 129
rpm-md repo 'copr:copr.fedorainfracloud.org:sentry:switcheroo-control_discrete' (cached); generated: 2024-09-07T08:21:49Z solvables: 5
rpm-md repo 'copr:copr.fedorainfracloud.org:che:nerd-fonts' (cached); generated: 2024-09-17T13:25:30Z solvables: 2
rpm-md repo 'copr:copr.fedorainfracloud.org:ublue-os:akmods' (cached); generated: 2024-10-31T03:51:19Z solvables: 116
rpm-md repo 'fedora-multimedia' (cached); generated: 2024-11-05T12:40:45Z solvables: 380
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2024-03-11T19:22:31Z solvables: 3
rpm-md repo 'fedora' (cached); generated: 2024-10-25T08:41:19Z solvables: 76624
rpm-md repo 'updates' (cached); generated: 2024-11-06T03:44:47Z solvables: 6296
rpm-md repo 'updates-archive' (cached); generated: 2024-11-06T04:12:58Z solvables: 5163
Resolving dependencies...done
Installing 1 packages:
  uld-1.00.39.12-2.fc41.x86_64 (fedora-multimedia)
Installing: uld-1.00.39.12-2.fc41.x86_64 (fedora-multimedia)
error: Error -1 running transaction
Error: building at STEP "RUN --mount=type=cache,dst=/var/cache/rpm-ostree --mount=type=bind,from=ctx,source=/,target=/ctx /ctx/build_files/shared/build-base.sh": while running runtime: exit status 1
```

If I had to guess, there's some script running via that RPM's spec file which isn't ostree friendly. But I haven't investigated further.

I will say, I'm glad our PR process is trustworthy enough we can test this before merging.

**Comment by fiftydinar** [comment]
@bsherman Weird thing is that `uld` installs successfully in my image

**Comment by bsherman** [comment]
> Weird thing is that `uld` installs successfully in my image

Link to the image build? Or do you mean it layers locally?  My explanation above allows for local layer install success.

**Comment by fiftydinar** [comment]
@bsherman Ah, I read better now. I meant in my image.

**Comment by tulilirockz** [comment]
i wonder where are the spec files for that ULD thing. worst case a little bit of patching wont do any harm. right?

**Comment by castrojo** [comment]
I'm +1 to these but taking over maintenance for printer drivers doesn't sound like a good time to me?

**Comment by bsherman** [comment]
@tulilirockz if you get this working in an image build and want to re-submit, that'll be good. For now, we'll close this.

**Pull request closed without merging**
