### PR TITLE
feat(aurora): replace logos and add new background wallpaper

### PR DESCRIPTION
**Pull request by NiHaiden**
This PR adds a refined Aurora Logo and the new wallpaper to the image and sets it as a default.

### CODE REVIEW

**Comment by fiftydinar** [comment]
Not sure if pixmap logo in ~2700px will work

**Review by m2Giles — COMMENTED** [review]
Windows should wobble.

**Comment by NiHaiden** [comment]
@m2Giles do you know by chance where the boot logo which appears in Plymouth needs to replaced? I looked everywhere but I think I am blind...

**Comment by m2Giles** [comment]
It replaces the default fedora one.

**Comment by m2Giles** [comment]
https://github.com/ublue-os/bluefin/tree/main/system_files%2Fshared%2Fusr%2Fshare%2Fplymouth%2Fthemes%2Fspinner

**Review by castrojo — APPROVED** [review]

**Pull request merged**
