### PR TITLE
feat(art): add some wallpapers

### PR DESCRIPTION
**Pull request by Xe**
I am donating these pictures to the Universal Blue project. Should you want to use these in Bazzite, feel free to. I hope these can give users some joy in the default config. These are some of my favorite pictures and sharing is caring.

Please let me know if you want more, I'm sure I can dig some up.

All of these except foothills.jpeg were shot on a Canon EOS R10.

Please let me know if I should lower the JPEG quality.

Photos are CC BY-SA 4.0.

### CODE REVIEW

**Comment by nicknamenamenick** [comment]
I think the sea needle image would work well for a default Bazzite wallpaper.

**Comment by Xe** [comment]
Let me know what I need to do to PR it to bazzite and it shall be done. What format do you want? 100% JPEG is pretty neutral but also disk-chonky. The files I PR'd here are slightly postprocessed with Affinity Photo, but I can reprocess it to any format you want.

**Review by bketelsen — DISMISSED** [review]

**Comment by Xe** [comment]
Can someone retry CI?

**Comment by bketelsen** [comment]
the asus builds are still failing :(

**Comment by castrojo** [comment]
Feel free to force a merge.

**Comment by fiftydinar** [comment]
Wallpapers are too big in size. 1MB & under is the recommendation.

Some slower hardware configurations would take some time to load the wallpaper.

Consider using JPEG-XL format for efficiently compressing the images without loosing quality.
[XL-Converter](https://github.com/JacobDev1/xl-converter/releases/tag/v0.9.8) is a good GUI program for this.

This is not a big deal, but just a nitpick.

**Comment by Xe** [comment]
Is there a way to seamlessly load multiple variants of a single wallpaper in the same .xml file? I shipped my files as 100% JPEG because I wanted to preserve quality for downstream compression. I am more than happy to create more lossy JXL versions.

I am also working on a git repo that will produce RPM files that can be consumed by projects such as bluefin and bazzite.

**Comment by fiftydinar** [comment]
> Is there a way to seamlessly load multiple variants of a single wallpaper in the same .xml file?

That is not currently possible.

> I shipped my files as 100% JPEG because I wanted to preserve quality for downstream compression.

That's understandable. I don't know which software for editing images are you using, but if you can export edited RAW photo as lossless & acceptable-losy JPEG-XL, It would be interesting to know what file-size it would be for those. I bet it would look the same in quality while having smaller file-size.

If you shoot those photos as JPEGs, then there's nothing that can be done to 100% preserve the quality. But maybe JPEG-XL can make the quality acceptable.


> I am also working on a git repo that will produce RPM files that can be consumed by projects such as bluefin and bazzite.

Nice

**Comment by Xe** [comment]
Is 85 quality JXL okay?

```
$ du -hs jxl* orig
41M     jxl-lossless
3.1M    jxl-85
51M     orig
```

https://xena.greedo.xeserv.us/files/xe_clouds.jxl (JXL 85%)

**Comment by fiftydinar** [comment]
> Is 85 quality JXL okay?

Looks great! Can't notice any difference even when peeping on my 4K 27 inch screen

**Comment by castrojo** [comment]
Nice catch on the file size, thanks for the keen review!

**Comment by Xe** [comment]
Would packages like this work? https://xena.greedo.xeserv.us/pkg/wallpapers/

**Comment by fiftydinar** [comment]
> Would packages like this work? [xena.greedo.xeserv.us/pkg/wallpapers](https://xena.greedo.xeserv.us/pkg/wallpapers/)

This looks good imo, I would ship it like this

**Review by castrojo — APPROVED** [review]

**Pull request merged**
