### PR TITLE
feat: add Ollama WebUI Just script

### PR DESCRIPTION
**Pull request by p5**
Creates the just script for setting up an Ollama WebUI quadlet.
We needed to implement a custom network to bypass the recent Pasta 🍝 Podman networking limitations, where it discourages you putting stuff on the host network.

### CODE REVIEW

**Comment by m2Giles** [comment]
On F40, podman is now podman 5 and defaults to Pasta for it's network backend. This is a breaking change from slirp4netns. 

The openwebui documentation calls out the necessary changes. I had to add the TCP port for the ollama quadlet and a host entry for it to work.

**Comment by ericcurtin** [comment]
open-webui works fine for me, but I'm still on `Fedora 39` and `podman version 4.9.4` though

https://github.com/ericcurtin/podman-ollama

**Comment by p5** [comment]
> open-webui works fine for me, but I'm still on `Fedora 39` and `podman version 4.9.4` though
> 
> https://github.com/ericcurtin/podman-ollama
> 

Yeah.  I need to add some extra args when using the default network, but when using a custom network, it works fine.  Will push the required args tonight

**Review by castrojo — APPROVED** [review]

**Comment by ericcurtin** [comment]
Upgraded just to see if I could reproduce on Fedora 40 and podman 5.

It worked, but I think you are right, it's because I set up a pod with it's own custom network

**Pull request merged**
