### PR TITLE
Added fix to the ptyxis-transparency command.

### LINKED ISSUE #1582: Fix `ptyxis opacity` command
Recommended command to change the opacity for ptyxis is incorrect:
```sh
ujust ptyxis-transparency opacity="0.99"
```

Correct:
```sh
ujust ptyxis-transparency "0.95"
```

### PR DESCRIPTION
**Pull request by dnikoloski**
Closes #1582

### CODE REVIEW

**Review by castrojo — APPROVED** [review]
Thanks for this! (I'll work on finishing it off)

**Comment by castrojo** [comment]
Kyle helped me debug this and he's able to set the transparency no problem, my computer seems to be busted. 

This is the correct command:

```
ujust ptyxis-transparency 0.95
```
But here's what the docs used to say (I just fixed them): 

```
ujust ptyxis-transparency opacity 0.95
```

So I think the command is correct, we've just been telling people to use it wrong?

**Comment by dnikoloski** [comment]
Yes, `ujust ptyxis-transparency 0.95` is the command it works for me too. Since you fixed the docs I will Close this PR.

**Comment by castrojo** [comment]
https://docs.projectbluefin.io/administration#adjusting-the-transparency

Documented here, thanks!

**Pull request closed without merging**
