### PR TITLE
fix(framework): added wallpaper xml

### LINKED ISSUE #437: Framework wallpapers need xml files
Need help with this, don't have the time to investigate. The wallpapers are in /usr/share/backgrounds. We need to add the xml files so they show up by default on the framework image. 

Bazzite has a script somewhere that helps generate these, but don't remember where it is.

### PR DESCRIPTION
**Pull request by bobslept**
Fixes #437 

Used this script [gen-xml-files.sh](https://github.com/ublue-os/bling/blob/main/build/backgrounds/gen-xml-files.sh) from the bling repo. Had to fiddle a little with the script to get the right paths. 

Added the xml files in `/usr/share/gnome-background-properties` and they are now selectable via `gnome-settings`

Maybe the `framework_box.svg` needs to be checked. it looks very bad. All others looked correct.

### CODE REVIEW

**Comment by castrojo** [comment]
cc @storyaddict - do you have cycles to track down a nicer svg from Framework?

**Comment by storyaddict** [comment]
I'll see if I can create some sub-processes to get this done. ;)

**Comment by bobslept** [comment]
I think I found the original here, they also a png variant. I could replace the svg one with the png one if you want?
https://community.frame.work/t/3-2-desktop-wallpapers/3533/7

**Comment by ctsdownloads** [comment]
Lemme see if I can dig something up.

**Comment by storyaddict** [comment]
It's Matt, Matt is sub-processes. lol. We're just multithreaded like that.

**Comment by ctsdownloads** [comment]
Yep, PNG is the way. This looks to be the best of the lot: https://static-community.frame.work/original/2X/3/35e24ff908d7bd41e6ca0865eda5a99f47c1e198.png 

Let @storyaddict  know if this works. :)

**Comment by storyaddict** [comment]
Image looks crystal clear to me. Thanks @ctsdownloads ! @bobslept does that work for you?

**Comment by bobslept** [comment]
i am testing it right now, expect a commit in a minute. Think it will work out!

**Comment by bobslept** [comment]
@castrojo  Would you want me to set it as default wallpaper for framework? Or leave it up to the user to change it.

**Review by storyaddict — APPROVED** [review]

**Review by castrojo — APPROVED** [review]

**Pull request merged**
